credentials:
  usernames:
    admin:
      email: admin@redi.com
      name: Admin User
      password: 1234567890
      role: admin

    supervisor:
      email: sup@redi.com
      name: Supervisor User
      password: 1234567890
      role: supervisor

    enumerator:
      email: enum@redi.com
      name: Enumerator User
      password: 1234567890
      role: enumerator

cookie:
  name: redi_cookie
  key: redi_secure_key
  expiry_days: 1
